# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CP_rejection <- function(n, mu, nu) {
    .Call(`_multcp_CP_rejection`, n, mu, nu)
}

delta_limits_cpp <- function(Z) {
    .Call(`_multcp_delta_limits_cpp`, Z)
}

rcompois <- function(n, mu, nu) {
    .Call(`_multcp_rcompois`, n, mu, nu)
}

ratio_IS_d_cpp <- function(d_R, lambda, nu, omega, N_aux) {
    .Call(`_multcp_ratio_IS_d_cpp`, d_R, lambda, nu, omega, N_aux)
}

ratios_IS_cpp <- function(lambda, nu, omega, N_aux) {
    .Call(`_multcp_ratios_IS_cpp`, lambda, nu, omega, N_aux)
}

est_logZinv_d_cpp <- function(d_R, lambda, nu, N_aux) {
    .Call(`_multcp_est_logZinv_d_cpp`, d_R, lambda, nu, N_aux)
}

est_logZinv_cpp <- function(lambda, nu, N_aux) {
    .Call(`_multcp_est_logZinv_cpp`, lambda, nu, N_aux)
}

update_propsd_double <- function(current_sd, accept_rate, nprops, target_ac = 0.44) {
    .Call(`_multcp_update_propsd_double`, current_sd, accept_rate, nprops, target_ac)
}

ln_proposal <- function(current_val, sigma) {
    .Call(`_multcp_ln_proposal`, current_val, sigma)
}

subset_nv <- function(vec, stop) {
    .Call(`_multcp_subset_nv`, vec, stop)
}

asymptotic_z <- function(lambda, nu) {
    .Call(`_multcp_asymptotic_z`, lambda, nu)
}

estimate_loglik <- function(Y, lambda, nu, delta, omega, N_aux_z, N_aux_r) {
    .Call(`_multcp_estimate_loglik`, Y, lambda, nu, delta, omega, N_aux_z, N_aux_r)
}

loglik_given_est <- function(Y, lambda, nu, delta, omega, ratios, log_inv_z) {
    .Call(`_multcp_loglik_given_est`, Y, lambda, nu, delta, omega, ratios, log_inv_z)
}

loglik_reg_given <- function(Y, X, gamma, nu, delta, omega, ratios, log_inv_z) {
    .Call(`_multcp_loglik_reg_given`, Y, X, gamma, nu, delta, omega, ratios, log_inv_z)
}

kernel <- function(Y, ratios, omega, delta) {
    .Call(`_multcp_kernel`, Y, ratios, omega, delta)
}

rmcomp_T <- function(n, lambda, nu, delta, omega, N_r, max_it = 1000L, tol = 0.001) {
    .Call(`_multcp_rmcomp_T`, n, lambda, nu, delta, omega, N_r, max_it, tol)
}

rmcomp_T_given <- function(n, lambda, nu, delta, omega, ratios, tol) {
    .Call(`_multcp_rmcomp_T_given`, n, lambda, nu, delta, omega, ratios, tol)
}

un_loglik_given <- function(dim_R, Y, lambda, nu, delta, omega, ratios) {
    .Call(`_multcp_un_loglik_given`, dim_R, Y, lambda, nu, delta, omega, ratios)
}

exchange_cpp <- function(Y, X, gamma, nu, delta, omega, ratios) {
    .Call(`_multcp_exchange_cpp`, Y, X, gamma, nu, delta, omega, ratios)
}

